package com.lanyan.mapper;

import java.util.List;

import com.lanyan.dto.BookShowDTO;
import com.lanyan.entity.BookShow;

public interface BookShowMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_show
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_show
     *
     * @mbg.generated
     */
    int insert(BookShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_show
     *
     * @mbg.generated
     */
    int insertSelective(BookShow record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_show
     *
     * @mbg.generated
     */
    BookShow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_show
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_show
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookShow record);
    
    
    /**
     * 
    * @Title: getBookList  
    * @Description: 获取书单列表 
    * @param @return    设定文件 
    * @return List<BookShowDTO>    返回类型  
    * @throws 
    * @author 王继波
    * @date 2018年2月27日 上午10:12:08
     */
    List<BookShowDTO> getBookList();
    
}