package com.lanyan.entity;

import java.util.Date;

public class BookShow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_show.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_show.book_id
     *
     * @mbg.generated
     */
    private String bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_show.book_type
     *
     * @mbg.generated
     */
    private String bookType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_show.book_discount
     *
     * @mbg.generated
     */
    private Double bookDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_show.book_deposit
     *
     * @mbg.generated
     */
    private Double bookDeposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_show.from_date
     *
     * @mbg.generated
     */
    private Date fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_show.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_show.station_code
     *
     * @mbg.generated
     */
    private String stationCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_show.id
     *
     * @return the value of book_show.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_show.id
     *
     * @param id the value for book_show.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_show.book_id
     *
     * @return the value of book_show.book_id
     *
     * @mbg.generated
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_show.book_id
     *
     * @param bookId the value for book_show.book_id
     *
     * @mbg.generated
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_show.book_type
     *
     * @return the value of book_show.book_type
     *
     * @mbg.generated
     */
    public String getBookType() {
        return bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_show.book_type
     *
     * @param bookType the value for book_show.book_type
     *
     * @mbg.generated
     */
    public void setBookType(String bookType) {
        this.bookType = bookType == null ? null : bookType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_show.book_discount
     *
     * @return the value of book_show.book_discount
     *
     * @mbg.generated
     */
    public Double getBookDiscount() {
        return bookDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_show.book_discount
     *
     * @param bookDiscount the value for book_show.book_discount
     *
     * @mbg.generated
     */
    public void setBookDiscount(Double bookDiscount) {
        this.bookDiscount = bookDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_show.book_deposit
     *
     * @return the value of book_show.book_deposit
     *
     * @mbg.generated
     */
    public Double getBookDeposit() {
        return bookDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_show.book_deposit
     *
     * @param bookDeposit the value for book_show.book_deposit
     *
     * @mbg.generated
     */
    public void setBookDeposit(Double bookDeposit) {
        this.bookDeposit = bookDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_show.from_date
     *
     * @return the value of book_show.from_date
     *
     * @mbg.generated
     */
    public Date getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_show.from_date
     *
     * @param fromDate the value for book_show.from_date
     *
     * @mbg.generated
     */
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_show.end_date
     *
     * @return the value of book_show.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_show.end_date
     *
     * @param endDate the value for book_show.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_show.station_code
     *
     * @return the value of book_show.station_code
     *
     * @mbg.generated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_show.station_code
     *
     * @param stationCode the value for book_show.station_code
     *
     * @mbg.generated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }
}